language: nodejs

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker build --pull --rm --tag hex0cter/alpine-x:latest .
  - docker tag hex0cter/alpine-x:latest hex0cter/alpine-x:$(git rev-parse --short HEAD)
  - docker push hex0cter/alpine-x:$(git rev-parse --short HEAD)
  - docker push hex0cter/alpine-x:latest
  - rm -f $HOME/.docker/config.json
